### PR TITLE
lift the state of Zkeys.js to App.js

### PR DESCRIPTION
**Pull request by ZakariaHn**
lift the state of Zkeys.js to App.js

### CODE REVIEW

**Comment by NLJZ** [comment]
Looks great to me!

**Comment by ZakariaHn** [comment]
I created the folder "controlers" and splited  each button from Zcontrolers.js into a separate reusable component

**Comment by NLJZ** [comment]
I like it!

**Comment by gabrielaacha** [comment]
looks good to me

**Comment by ZakariaHn** [comment]
created a new file "ZwaveFormController". this component will allow the user to change the form of the wave 

If it's ok for you please merge it immediately  to the master branch

**Pull request merged**
