### PR TITLE
delay button

### PR DESCRIPTION
**Pull request by ZakariaHn**
delay button added

### CODE REVIEW

**Comment by NLJZ** [comment]
Looks cool. Looks like we might need some logic to turn the delay on/off? Or will it always be on and then sometimes the setting is just to zero?

**Comment by ZakariaHn** [comment]
good Idea, will work on that either tonight or tomorrow

**Comment by NLJZ** [comment]
if you giving something like delay or volume a setting of null will it just shut off but not break the synth?

**Comment by ZakariaHn** [comment]
the Initial value for delay is 0, and if you change the value  to 0 for what ever controller the synth keep working!!

why would it break ?

**Pull request merged**
